version: '3'

services:

  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mediamarktdb

  mediamarktbackend:
    build: ./
    container_name: media_markt_backend
    image: mediamarkt/backend:version1.0
    ports:
      - "8081:8081"
    depends_on:
      - dbpostgresql
