version: '3'

services:

  mediamarktbackend:
    build: ./
    container_name: media_markt_backend
    image: mediamarkt/backend:version1.0
    ports:
      - "8081:8081"

  mediamarktfrontend:
    build: ./src/main/angular/MediaMarktApp/
    container_name: media_markt_frontend
    ports:
      - "80:80"
